language: node_js
node_js:
  - node


before_install: 
  - npm i -g yarn
  - npm i -g mocha

jobs:
  include:
    - os: windows
      env: WINDOWS=TRUE
      before_install: 
        - powershell Set-ExecutionPolicy -ExecutionPolicy unrestricted
        - npm i -g mocha
      after_script:
        - powershell "exit 0"
      install: yarn preparewindows
    - dist: xenial
      env: WINDOWS=FALSE
      install: yarn prepare
